// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repository.Models;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(ItemContext))]
    [Migration("20240903103034_GeladeiMigration")]
    partial class GeladeiMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Repository.Models.Item", b =>
                {
                    b.Property<int>("IdItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_ITEM");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdItem"));

                    b.Property<int?>("Andar")
                        .HasColumnType("int")
                        .HasColumnName("ANDAR");

                    b.Property<string>("Classificacao")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("CLASSIFICACAO");

                    b.Property<int?>("Container")
                        .HasColumnType("int")
                        .HasColumnName("CONTAINER");

                    b.Property<string>("DescricaoItem")
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)")
                        .HasColumnName("DESCRICAO_ITEM");

                    b.Property<int?>("Posicao")
                        .HasColumnType("int")
                        .HasColumnName("POSICAO");

                    b.Property<int?>("Quantidade")
                        .HasColumnType("int")
                        .HasColumnName("QUANTIDADE");

                    b.Property<string>("Unidade")
                        .HasMaxLength(5)
                        .IsUnicode(false)
                        .HasColumnType("varchar(5)")
                        .HasColumnName("UNIDADE");

                    b.HasKey("IdItem")
                        .HasName("PK_ID_ITEM");

                    SqlServerKeyBuilderExtensions.IsClustered(b.HasKey("IdItem"), false);

                    b.ToTable("ITEM", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
